### PR TITLE
Changelog for 0.60.

### PR DESCRIPTION
**Pull request by lang-m**

### CODE REVIEW

**Comment by marijanbeg** [comment]
@lang-m, very cool :)

**Comment by lang-m** [comment]
@marijanbeg We should think about moving the changelog file to the website repository. I guess most people will read the changelog on the website anyway. At the moment the `rst` file shows up on Binder (probably confusing for some). And we really don't need to run the tests every time we update the changelog.

**Comment by marijanbeg** [comment]
I agree, @lang-m. It is only important we have it in one place for simplicity.

**Comment by lang-m** [comment]
I have moved the changelog to the website repo (https://github.com/ubermag/ubermag.github.io/pull/1/commits/286b052b444fecb05a529e7602481b027d520b22)

**Pull request closed without merging**
